"""Data models for vouchers and voucher codes."""

from __future__ import annotations

import dataclasses
from datetime import datetime

from ticketmatic.models.base import Model


@dataclasses.dataclass
class VoucherValidity(Model):
    """The definition of the validity of a voucher."""

    expiry_fixeddate: datetime | None = None
    """The fixed expiry date for a voucher.

    The voucher will be valid until this date (thus if 2020-01-01 is
    specified, the voucher will remain valid until 2019-12-31 23:59:59).
    If this is specified, it has preference over
    ``expiry_monthsaftercreation``.
    """
    expiry_monthsaftercreation: int | None = None
    """The relative expiry date for a voucher: voucher code expires this
    number of months after creation. If ``expiry_fixeddate`` is specified,
    this field is ignored.
    """
    maxusages: int | None = None
    """The max number of times the vouchercode can be used.

    This field is only relevant for pricetype vouchers.
    """
    maxusagesperevent: int | None = None
    """The max number of times the vouchercode can be used for a single event.

    This field is only relevant for pricetype vouchers.
    """


@dataclasses.dataclass
class VoucherCode(Model):
    """Voucher code."""

    code: str | None = None
    """Code to use voucher."""
    expiryts: datetime | None = None
    """Expiry timestamp for this code."""


@dataclasses.dataclass
class Voucher(Model):
    """A single voucher."""

    id: int | None = None
    """Unique ID.

    **Note:** Ignored when creating a new voucher.

    **Note:** Ignored when updating an existing voucher.
    """
    typeid: int | None = None
    """Type ID.

    **Note:** Ignored when updating an existing voucher.
    """
    name: str | None = None
    """Name of the voucher."""
    codeformatid: int | None = None
    """Format used when generating codes for the voucher. Possible values:

    * **27001**: 12 digits
    * **27002**: 16 digits
    * **27003**: 8 alphanumerical characters
    * **27004**: 12 alphanumerical characters
    * **27005**: 16 alphanumerical characters
    * **27099**: Specified from list, not autogenerated
    """
    codeprefix: str | None = None
    """Prefix prepended to generated codes to ensure uniqueness.

    If set, generated codes are padded with this prefix. The prefix can be
    at most 10 characters long.

    **Note:** Not set when retrieving a list of vouchers.
    """
    description: str | None = None
    """Description of the voucher."""
    nbrofcodes: int | None = None
    """The number of codes that were created for this voucher.

    **Note:** Ignored when creating a new voucher.

    **Note:** Ignored when updating an existing voucher.
    """
    ordervalidationscript: str | None = None
    """Validation script used for vouchers of type order.

    For each order with a voucher of this type attached, the script will
    be run to validate the contents.
    """
    paymentmethodid: int | None = None
    """Payment method to use when creating payments for vouchers of type
    ``payment``.

    This field is required when a ``payment`` voucher is created. The
    payment method referred to should be of a ``voucher`` type.
    """
    validity: VoucherValidity | None = None
    """Definition of the validity of this voucher. Depends on the typeid.

    **Note:** Not set when retrieving a list of vouchers.
    """
    isarchived: bool | None = None
    """Whether or not this item is archived.

    **Note:** Ignored when creating a new voucher.

    **Note:** Ignored when updating an existing voucher.
    """
    createdts: datetime | None = None
    """Created timestamp.

    **Note:** Ignored when creating a new voucher.

    **Note:** Ignored when updating an existing voucher.
    """
    lastupdatets: datetime | None = None
    """Last updated timestamp.

    **Note:** Ignored when creating a new voucher.

    **Note:** Ignored when updating an existing voucher.
    """


@dataclasses.dataclass
class VoucherQuery(Model):
    """Set of parameters used to filter vouchers."""

    typeid: int | None = None
    """Only return items with the given typeid."""
    filter: str | None = None
    """Filter the returned items by specifying a query on the public datamodel
    that returns the ids.
    """
    includearchived: bool | None = None
    """If this parameter is true, archived items will be returned as well."""
    lastupdatesince: datetime | None = None
    """All items updated since this timestamp will be returned.

    Timestamp should be passed in ``YYYY-MM-DD hh:mm:ss`` format.
    """


@dataclasses.dataclass
class AddVoucherCodes(Model):
    """Parameters used to create voucher codes."""

    amount: float | None = None
    """Value of the voucher."""
    codes: list[VoucherCode] | None = None
    """List of voucher codes, can also optionally contain expiry timestamps."""
    count: int | None = None
    """Number of codes to create."""
    update: bool | None = None
    """Whether or not to reactivate and update the expiry of already existing
    voucher codes.
    """
